#pragma once

#include <stddef.h>

struct IataAirportCity {
    const char *iata;
    const char *city;
};

static const IataAirportCity kIataAirportCities[] = {
    {"ACE", "Lanzarote"},
    {"AGP", "Malaga"},
    {"ALC", "Alicante"},
    {"AMS", "Amsterdam"},
    {"ARN", "Stockholm"},
    {"ATH", "Athens"},
    {"BCN", "Barcelona"},
    {"BER", "Berlin"},
    {"BFS", "Belfast"},
    {"BHX", "Birmingham"},
    {"BIO", "Bilbao"},
    {"BOD", "Bordeaux"},
    {"BRI", "Bari"},
    {"BRS", "Bristol"},
    {"BRU", "Brussels"},
    {"BUD", "Budapest"},
    {"CDG", "Paris"},
    {"CIA", "Rome"},
    {"CPH", "Copenhagen"},
    {"DUB", "Dublin"},
    {"DUS", "Dusseldorf"},
    {"EDI", "Edinburgh"},
    {"EIN", "Eindhoven"},
    {"EMA", "Nottingham"},
    {"FCO", "Rome"},
    {"FRA", "Frankfurt"},
    {"FUE", "Fuerteventura"},
    {"GDN", "Gdansk"},
    {"GLA", "Glasgow"},
    {"GRO", "Girona"},
    {"GVA", "Geneva"},
    {"HAM", "Hamburg"},
    {"HEL", "Helsinki"},
    {"IBZ", "Ibiza"},
    {"IST", "Istanbul"},
    {"LCG", "A Coruna"},
    {"LCY", "London"},
    {"LED", "Saint Petersburg"},
    {"LEJ", "Leipzig"},
    {"LGW", "London"},
    {"LIN", "Milan"},
    {"LIS", "Lisbon"},
    {"LPA", "Gran Canaria"},
    {"LPL", "Liverpool"},
    {"LTN", "London"},
    {"LUX", "Luxembourg"},
    {"LWO", "Lviv"},
    {"MAD", "Madrid"},
    {"MAH", "Menorca"},
    {"MAN", "Manchester"},
    {"MRS", "Marseille"},
    {"MUC", "Munich"},
    {"MXP", "Milan"},
    {"NAP", "Naples"},
    {"NCE", "Nice"},
    {"NCL", "Newcastle"},
    {"OPO", "Porto"},
    {"ORY", "Paris"},
    {"OSL", "Oslo"},
    {"OVD", "Oviedo"},
    {"PMI", "Palma"},
    {"PMO", "Palermo"},
    {"PRG", "Prague"},
    {"PSA", "Pisa"},
    {"REU", "Reus"},
    {"RIX", "Riga"},
    {"SCQ", "Santiago"},
    {"SDR", "Santander"},
    {"SOF", "Sofia"},
    {"STN", "London"},
    {"SVQ", "Seville"},
    {"TFN", "Tenerife"},
    {"TFS", "Tenerife"},
    {"TLS", "Toulouse"},
    {"TRN", "Turin"},
    {"VCE", "Venice"},
    {"VGO", "Vigo"},
    {"VIE", "Vienna"},
    {"VLC", "Valencia"},
    {"WAW", "Warsaw"},
    {"ZRH", "Zurich"},
};

static constexpr size_t kIataAirportCityCount = sizeof(kIataAirportCities) / sizeof(kIataAirportCities[0]);

